#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/polyMesh/boundary

# Remove rest.txt
\rm -f system/rest.txt

# remove fort.90 
\rm -f fort.90
