#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

#--------------------------------------
#               Fluid     
#--------------------------------------

# Meshing fluid domain 
runApplication blockMesh

runApplication $application &

# ----------------------------------------------------------------- end-of-file
