#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Get application name from directory
application=`basename $PWD`

casefiles="CSM3 CFD3 FSI3"

# Enter into CSM3 Directory

for case in $casefiles
do
   (cd $case && cleanCase && rm -f constant/polyMesh/boundary)

done
# ----------------------------------------------------------------- end-of-file
