#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application=`basename $PWD`

casefiles="CSM3 CFD3 FSI3"

# Enter into CSM3 Directory

for case in $casefiles
do
   (cd $case && runApplication blockMesh)

#   if [ "$case" = "CSM3" ]
#   then
#       (cd $case && runApplication solidFoam)
#   fi

#   if [ "$case" = "CFD3" ]
#   then
#       (cd $case && runApplication fluidFoam)
#   fi
 
    if [ "$case" == "FSI3"]
    then
      (cd $case && runApplication fsiFoam)
    fi

done
# ----------------------------------------------------------------- end-of-file
